quarkus.application.name=fintrack-app
quarkus.http.root-path=/api/v1
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/postgres?curentSchema=fintrack
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=isosra
quarkus.hibernate-orm.database.generation = update
quarkus.hibernate-orm.database.version-check.enabled=false

