quarkus.http.host=0.0.0.0
quarkus.http.port=8080
quarkus.application.name=fintrack-app
quarkus.http.root-path=/api/v1

quarkus.datasource.jdbc.url=${QUARKUS_DATASOURCE_JDBC_URL:jdbc:postgresql://localhost:5432/postgres?curentSchema=fintrack}
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${QUARKUS_DATASOURCE_USERNAME:postgres}
quarkus.datasource.password=${QUARKUS_DATASOURCE_PASSWORD:isosra}
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.database.version-check.enabled=false

# Emissor
mp.jwt.verify.issuer=fintrack-api
smallrye.jwt.sign.key.location=${PRIVATE_KEY:rsaPrivateKey.pem}
mp.jwt.verify.publickey.location=${PUBLIC_KEY:publicKey.pem}
smallrye.jwt.log-token=true
quarkus.log.category."io.smallrye.jwt".level=DEBUG